### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by vangoespow**
merge of develop into master for iteration 1

### CODE REVIEW

**Comment by ryancanavan** [comment]
Should we merge the web slider and docker changes into dev before we merge with master? I'm fine either way.

**Comment by vangoespow** [comment]
> Should we merge the web slider and docker changes into dev before we merge with master? I'm fine either way.

I think they are still working on those

**Comment by shi24** [comment]
There are 3 known defects that needs to be fixed for the web slider, but besides that it's "functional" lol

**Comment by vangoespow** [comment]
> There are 3 known defects that needs to be fixed for the web slider, but besides that it's "functional" lol

We can probably wait until next iteration to merge your stuff into master then if there are open bugs.

**Comment by shi24** [comment]
Yea I'm fine with it. I just didn't bother fixing it because I thought we came to conclusion that we were not continuing the web application aspect.

**Review by ryancanavan — APPROVED** [review]

**Pull request merged**
